[project]
name = "youtube2opus"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "audiosr>=0.0.7",
    "deepfilternet>=0.5.6",
    "mutagen>=1.47.0",
    "pydub>=0.25.1",
    "yt-dlp>=2025.11.12",
]

[dependency-groups]
dev = [
    "black>=25.11.0",
]
